---
title: "LT Public Finance Dashboard"
author: "Žygimantas Bogužas"
format: dashboard
embed-resources: true
---

```{r include=FALSE}
#| label: Packages
#| include: false
if(!require("pacman")) install.packages("pacman");library("pacman")
p_load(eurostat, rsdmx, data.table, janitor, zoo, plotly, DT)
```

```{r include=FALSE}
#| label: Functions
#| include: false

yoy_growth <- function(x) {(x/shift(x, n=12, type = "lag"))*100-100}
kv_calc <- function(x, y) {(shift(x, n=12, type = "lag")/shift(y, n=12, type = "lag"))*(x/shift(x, n=12, type = "lag")-1)*100}
```

# Centrinė valdžia {orientation="rows"}

## {.tabset}

### Charts {.panel-tabset}
```{r}
#| label: CV data prep
#| include: false
total_variables <- c("Pajamos", "Mokesčiai", "Socialinės įmokos", "Dotacijos_p", "Kitos pajamos",
                     "Išlaidos", "Darbo užmokestis ir socialinis draudimas", "Prekių ir paslaugų naudojimas", "Palūkanos", "Subsidijos", "Dotacijos_i", "Socialinės išmokos", "Kitos išlaidos")

pajamos_vars <- c("Pajamos", "Mokesčiai", "Socialinės įmokos", "Dotacijos_p", "Kitos pajamos")

islaidos_vars <- c("Išlaidos", "Darbo užmokestis ir socialinis draudimas", "Prekių ir paslaugų naudojimas", "Palūkanos", "Subsidijos", "Dotacijos_i", "Socialinės išmokos", "Kitos išlaidos")

dt_CV <- as.data.table(readSDMX(providerId = "LSD", resource = "data", flowRef = "S7R283_M2040105", dsd = TRUE), labels = T)

dt_CV_growth_kv <- dt_CV[, clean_names(dt_CV)
                         ][, kintamasis := fcase(deficitas_m60808 == "R04","Dotacijos_p",
                                                 deficitas_m60808 == "R11","Dotacijos_i",
                                                 deficitas_m60808 == "R21","Vidaus (Grynasis finansinio turto pasikeitimas, išskyrus grynuosius pinigus)",
                                                 deficitas_m60808 == "R22","Užsienio (Grynasis finansinio turto pasikeitimas, išskyrus grynuosius pinigus)",
                                                 deficitas_m60808 == "R24","Vidaus (Grynasis finansinių įsipareigojimų pasikeitimas)",
                                                 deficitas_m60808 == "R25","Užsienio (Grynasis finansinių įsipareigojimų pasikeitimas)",
                                                 rep(TRUE, .N), deficitas_m60808_label_lt)
                           ][, .(laikotarpis, kintamasis, obs_value)
                             ][, laikotarpis := as.Date(as.yearmon(laikotarpis, format = "%YM%m"))
                               ][, dcast(.SD, laikotarpis ~ kintamasis, value.var = "obs_value")
                                 ][, paste0(total_variables, "_yoy_growth") := lapply(.SD, yoy_growth), .SDcols = total_variables
                                   ][, paste0(pajamos_vars, "_kv") := lapply(.SD, kv_calc, y = Pajamos), .SDcols = pajamos_vars
                                     ][, paste0(islaidos_vars, "_kv") := lapply(.SD, kv_calc, y = Išlaidos), .SDcols = islaidos_vars
                                       ][, clean_names(.SD)]

```

#### Column1 {.tabset}

```{r}
#| label: CV pajamų metinis augimas ir kaitos veiksniai
#| title: Pajamų metinis augimas ir kaitos veiksniai
#| warning: false
#| padding: 0px

dt_CV_p_kv <- dt_CV_growth_kv[,.(laikotarpis, pajamos_kv, mokesciai_kv, socialines_imokos_kv, dotacijos_p_kv, kitos_pajamos_kv)
                            ][,melt(.SD, measure.vars = 2:ncol(.SD))
                              ][!is.na(value)
                                ][,variable := fcase(variable == "pajamos_kv", "Pajamos",
                                                     variable == "mokesciai_kv", "Mokesčiai",
                                                     variable == "socialines_imokos_kv", "Socialinės įmokos",
                                                     variable == "dotacijos_p_kv", "Dotacijos",
                                                     variable == "kitos_pajamos_kv", "Kitos pajamos")
                                  ][, value := round(value, 1)]
  
plot_ly() |>
  add_trace(data = dt_CV_p_kv[variable != "Pajamos"], 
            x = ~laikotarpis, 
            y = ~value, 
            type = "bar", 
            name = ~variable, 
            color = ~variable) |> 
  layout(barmode = "relative", 
         showlegend = F, 
         xaxis = list(title = "", tickformat= "%Y-%m"), 
         yaxis = list(title="")) |> 
  add_trace(data = dt_CV_p_kv[variable == "Pajamos"], 
            x = ~laikotarpis, 
            y = ~value, 
            type = "scatter", 
            mode = "lines+markers", 
            color = ~variable, 
            line = list(color = "black", width = 3), 
            marker = list(color = "black", size = 8)) |> 
  config(modeBarButtonsToRemove = c("lasso2d", "zoom2d", "zoomIn2d", "zoomOut2d", "select2d", "pan2d", "resetScale2d"), 
         displaylogo = F)
```
```{r}
#| label: CV pajamų ir dedamųjų metiniai augimo tempai
#| title: Metiniai augimo tempai %
#| warning: false
#| padding: 0px

dt_CV_p_gr <- dt_CV_growth_kv[,.(laikotarpis, pajamos_yoy_growth, mokesciai_yoy_growth, socialines_imokos_yoy_growth, dotacijos_p_yoy_growth, kitos_pajamos_yoy_growth)
                            ][,melt(.SD, measure.vars = 2:ncol(.SD))
                              ][!is.na(value)
                                ][,variable := fcase(variable == "pajamos_yoy_growth", "Pajamos",
                                                     variable == "mokesciai_yoy_growth", "Mokesčiai",
                                                     variable == "socialines_imokos_yoy_growth", "Socialinės įmokos",
                                                     variable == "dotacijos_p_yoy_growth", "Dotacijos",
                                                     variable == "kitos_pajamos_yoy_growth", "Kitos pajamos")
                                  ][, value := round(value, 1)]
  
plot_ly() |>
  add_trace(data = dt_CV_p_gr, 
            x = ~laikotarpis, 
            y = ~value, 
            type = "scatter", 
            mode = "lines+markers", 
            name = ~variable,
            color = ~variable) |>
  layout(xaxis = list(title = "", tickformat= "%Y-%m"), 
         yaxis = list(title=""), 
         legend = list(orientation = "h", y = 10)) |>
  config(modeBarButtonsToRemove = c("lasso2d", "select2d", "resetScale2d"), 
         displaylogo = F,
         scrollZoom = T)
```


```{r}
#| label: CV pajamos nominalia išraiška
#| title: Pajamos mln. €
#| warning: false
#| padding: 0px

dt_CV_p_nom <- dt_CV_growth_kv[,.(laikotarpis, pajamos, mokesciai, socialines_imokos, dotacijos_p, kitos_pajamos)
                            ][,melt(.SD, measure.vars = 2:ncol(.SD))
                              ][!is.na(value)
                                ][,variable := fcase(variable == "pajamos", "Pajamos",
                                                     variable == "mokesciai", "Mokesčiai",
                                                     variable == "socialines_imokos", "Socialinės įmokos",
                                                     variable == "dotacijos_p", "Dotacijos",
                                                     variable == "kitos_pajamos", "Kitos pajamos")
                                  ][, value := round(value, 0)]
  
plot_ly() |>
  add_trace(data = dt_CV_p_nom[variable != "Pajamos"], 
            x = ~laikotarpis, 
            y = ~value, type = "bar", 
            name = ~variable, 
            color = ~variable) |> 
  layout(barmode = "relative", 
         showlegend = F, 
         xaxis = list(title = "", tickformat= "%Y-%m"), 
         yaxis = list(title="")) |> 
  add_trace(data = dt_CV_p_nom[variable == "Pajamos"], 
            x = ~laikotarpis, 
            y = ~value, 
            type = "scatter", 
            mode = "lines+markers", 
            color = ~variable, 
            line = list(color = "black", width = 3), 
            marker = list(color = "black", size = 8)) |> 
  config(modeBarButtonsToRemove = c("lasso2d", "zoom2d", "zoomIn2d", "zoomOut2d", "select2d", "resetScale2d"), 
         displaylogo = F)

```

#### Column2 {.tabset}

```{r}
#| label: CV išlaidų metinis augimas ir kaitos veiksniai
#| title: Išlaidų metinis augimas ir kaitos veiksniai
#| warning: false
#| padding: 0px

dt_CV_i_kv <- dt_CV_growth_kv[,.(laikotarpis, islaidos_kv, darbo_uzmokestis_ir_socialinis_draudimas_kv, prekiu_ir_paslaugu_naudojimas_kv, palukanos_kv, subsidijos_kv, dotacijos_i_kv, socialines_ismokos_kv, kitos_islaidos_kv)
                            ][,melt(.SD, measure.vars = 2:ncol(.SD))
                              ][!is.na(value)
                                ][,variable := fcase(variable == "islaidos_kv", "Išlaidos",
                                                     variable == "darbo_uzmokestis_ir_socialinis_draudimas_kv", "Darbo užmokestis ir socialinis draudimas",
                                                     variable == "prekiu_ir_paslaugu_naudojimas_kv", "Prekių ir paslaugų naudojimas",
                                                     variable == "palukanos_kv", "Palūkanos",
                                                     variable == "subsidijos_kv", "Subsidijos",
                                                     variable == "dotacijos_i_kv", "Dotacijos",
                                                     variable == "socialines_ismokos_kv", "Socialinės išmokos",
                                                     variable == "kitos_islaidos_kv", "Kitos išlaidos")
                                  ][, value := round(value, 1)]
  
plot_ly() |>
  add_trace(data = dt_CV_i_kv[variable != "Išlaidos"], 
            x = ~laikotarpis, 
            y = ~value, 
            type = "bar", 
            name = ~variable,
            color = ~variable) |> 
  layout(barmode = "relative", 
         showlegend = F, 
         xaxis = list(title = "", tickformat= "%Y-%m"), 
         yaxis = list(title="")) |> 
  add_trace(data = dt_CV_i_kv[variable == "Išlaidos"], 
            x = ~laikotarpis, 
            y = ~value, 
            type = "scatter",
            mode = "lines+markers", 
            color = ~variable, 
            line = list(color = "black", width = 3), 
            marker = list(color = "black", size = 8)) |> 
  config(modeBarButtonsToRemove = c("lasso2d", "zoom2d", "zoomIn2d", "zoomOut2d", "select2d", "pan2d", "resetScale2d"), 
         displaylogo = F)

```

```{r}
#| label: CV išlaidų ir dedamųjų metiniai augimo tempai
#| title: Metiniai augimo tempai %
#| warning: false
#| padding: 0px

dt_CV_i_gr <- dt_CV_growth_kv[,.(laikotarpis, islaidos_yoy_growth, darbo_uzmokestis_ir_socialinis_draudimas_yoy_growth, prekiu_ir_paslaugu_naudojimas_yoy_growth, palukanos_yoy_growth, subsidijos_yoy_growth, dotacijos_i_yoy_growth, socialines_ismokos_yoy_growth, kitos_islaidos_yoy_growth)
                            ][,melt(.SD, measure.vars = 2:ncol(.SD))
                              ][!is.na(value)
                                ][,variable := fcase(variable == "islaidos_yoy_growth", "Išlaidos",
                                                     variable == "darbo_uzmokestis_ir_socialinis_draudimas_yoy_growth", "Darbo užmokestis ir socialinis draudimas",
                                                     variable == "prekiu_ir_paslaugu_naudojimas_yoy_growth", "Prekių ir paslaugų naudojimas",
                                                     variable == "palukanos_yoy_growth", "Palūkanos",
                                                     variable == "subsidijos_yoy_growth", "Subsidijos",
                                                     variable == "dotacijos_i_yoy_growth", "Dotacijos",
                                                     variable == "socialines_ismokos_yoy_growth", "Socialinės išmokos",
                                                     variable == "kitos_islaidos_yoy_growth", "Kitos išlaidos")
                                  ][, value := round(value, 1)]
  
plot_ly() |>
  add_trace(data = dt_CV_i_gr, 
            x = ~laikotarpis, 
            y = ~value, 
            type = "scatter", 
            mode = "lines+markers", 
            name = ~variable, 
            color = ~variable)|>
  layout(xaxis = list(title = "", tickformat= "%Y-%m"), 
         yaxis = list(title=""), 
         legend = list(orientation = "h", y = 100)) |> 
  config(modeBarButtonsToRemove = c("lasso2d", "select2d", "resetScale2d"), 
         displaylogo = F,
         scrollZoom = T)
```

```{r}
#| label: CV išlaidos nominalia išraiška
#| title: Išlaidos mln. €
#| warning: false
#| padding: 0px

dt_CV_i_nom <- dt_CV_growth_kv[,.(laikotarpis, islaidos, darbo_uzmokestis_ir_socialinis_draudimas, prekiu_ir_paslaugu_naudojimas, palukanos, subsidijos, dotacijos_i, socialines_ismokos, kitos_islaidos)
                            ][,melt(.SD, measure.vars = 2:ncol(.SD))
                              ][!is.na(value)
                                ][,variable := fcase(variable == "islaidos", "Išlaidos",
                                                     variable == "darbo_uzmokestis_ir_socialinis_draudimas", "Darbo užmokestis ir socialinis draudimas",
                                                     variable == "prekiu_ir_paslaugu_naudojimas", "Prekių ir paslaugų naudojimas",
                                                     variable == "palukanos", "Palūkanos",
                                                     variable == "subsidijos", "Subsidijos",
                                                     variable == "dotacijos_i", "Dotacijos",
                                                     variable == "socialines_ismokos", "Socialinės išmokos",
                                                     variable == "kitos_islaidos", "Kitos išlaidos")
                                  ][, value := round(value, 0)]
  

plot_ly() |>
  add_trace(data = dt_CV_i_nom[variable != "Išlaidos"], 
            x = ~laikotarpis, 
            y = ~value, 
            type = "bar", 
            name = ~variable, 
            color = ~variable) |> 
  layout(barmode = "relative", 
         showlegend = F, 
         xaxis = list(title = "", tickformat= "%Y-%m"), 
         yaxis = list(title="")) |> 
  add_trace(data = dt_CV_i_nom[variable == "Išlaidos"], 
            x = ~laikotarpis, 
            y = ~value, type = "scatter", 
            mode = "lines+markers", 
            color = ~variable, 
            line = list(color = "black", width = 3), 
            marker = list(color = "black", size = 8)) |> 
  config(modeBarButtonsToRemove = c("lasso2d", "zoom2d", "zoomIn2d", "zoomOut2d", "select2d", "resetScale2d"), 
         displaylogo = F)

```

### Data

```{r}
#| label: CV Data
#| warning: false
#| padding: 0px

dt_CV_growth_kv[, 2:ncol(dt_CV_growth_kv) := lapply(.SD, round, 1), .SDcols = 2:ncol(dt_CV_growth_kv)
                ][, datatable(data = .SD, rownames = F, filter = "top", extensions = c("Buttons","Scroller"), options = list(dom = "BSltpr", 
                                                                                                 buttons = c("copy","excel","pdf"), 
                                                                                                 autoWidth = TRUE,
                                                                                                 paging = TRUE,
                                                                                                 scroller = TRUE,
                                                                                                 scrollY = 585,
                                                                                                 scrollX = TRUE))]
```

# Valdžios sektorius {orientation="rows"}

## {.tabset}

### Charts {.panel-tabset}
```{r}
#| label: VS data prep
#| include: false

dt_VS <- as.data.table(readSDMX(providerId = "LSD", resource = "data", flowRef = "S7R268_M2040217", dsd = TRUE), labels = T)

dt_VS_growth_kv <- dt_VS[sektoriusM6020205 == "S13", clean_names(.SD)
                         ][, variable := paste(sandoris_m2040217_label_lt, sandoris_m2040217, sep = "_")
                           ][, .(laikotarpis, variable, obs_value)
                             ][, laikotarpis := as.Date(as.yearqtr(laikotarpis, format = "%YK%q"))
                               ][, dcast(.SD, laikotarpis ~ variable, value.var = "obs_value")
                                 ]
```



